image:
  file: .gitpod.Dockerfile

tasks:
  - name: Lume
    command: lume --serve

vscode:
  extensions:
    - denoland.vscode-deno

ports:
  - port: 3000
    onOpen: open-browser
    visibility: private