image:
  file: .gitpod.Dockerfile

tasks:
  - name: Cloudflare Pages
    command: |
      npm install wrangler
      npx wrangler pages dev _site
  - name: Lume
    command: |
      gp env -e
      lume --serve

vscode:
  extensions:
    - denoland.vscode-deno

ports:
  - port: 3000
    onOpen: ignore  
  - port: 8788
    onOpen: open-browser
    visibility: private