#!/usr/bin/expect -f

set timeout 30

spawn sftp -o StrictHostKeyChecking=no -P 22 u102640071@access848044507.webspace-data.io

expect "password:"
send "Ionos2025!!Ionos2025!!\r"

expect "sftp>"
send "cd /production/research\r"

expect "sftp>"
send "rm images/european-management-quarterly.jpg\r"

expect "sftp>"
send "rmdir images\r"

expect "sftp>"
send "cd ..\r"

expect "sftp>"
send "rmdir research\r"

expect "sftp>"
send "quit\r"

interact